
onix-legacy-api:
  enabled: true
  nameOverride: onix-legacy-api

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    securityContext:
      fsGroup: apache2

    initContainers:
      - name: volume-dirs-init-cntr
        image: busybox:1.35
        command:
        - "/bin/mkdir"
        args:
        - "-p"
        - "/wis/data/wip"
        - "/wis/data/locked"
        - "/wis/data/storage"
        - "/wis/data/sessions"
        volumeMounts:
        - name: data-dir
          mountPath: "/wis/data"

    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/onix/onix-legacy-api
    imagePullSecrets:
      - name: gar-image-pull

    volumeMounts:
      - name: data-dir
        mountPath: /wis/data
    volumes:
      - name: data-dir
        persistentVolumeClaim:
          claimName: onix-data

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
