onix-legacy-api:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 30m
        memory: 128Mi

    env:
      - name: ONIX_STAGE
        value: "dev"

      - name: WIS_CORE_ENCRYPTED
        value: "false"

      - name: POST_PARAM_NAME
        value: "xxxxx"

      - name: ONIX_SESSION_DIR
        value: "/wis/data/sessions"

      - name: ONIX_WIP_DIR
        value: "/wis/data/wip"

      - name: ONIX_LOCK_DIR
        value: "/wis/data/locked"

      - name: ONIX_STORAGE_DIR
        value: "/wis/data/storage"

      - name: ONIX_DSN
        value: "dbname=onix;host=postgresql-svc;port=5432"

      - name: ONIX_DB_USERNAME
        value: "postgres"

      - name: ONIX_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret 
            key: adminPasswordKey
            optional: false
