apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onix-legacy-content-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.onixLegacyApiDomain }}"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/onix/api/acd/acdesign/content.php"
        backend:
          service:
            name: onix-{{ .Values.envAlias }}-onix-legacy-api
            port:
              number: 80
