apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onix-legacy-api-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Onix API'
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.onixLegacyApiDomain }}"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: onix-{{ .Values.envAlias }}-onix-legacy-api
            port:
              number: 80
